# Configuration for AzusaMath plugin

number_max: 100

# Time lapse for maths problems to be answered
problem_interval: 60

# Message when the player successfully answers the maths question
maths_completion_message: "§aCongratulations! §e{player} §asuccessfully answered the maths question correctly §6{money} §aMoney"

# Message when no one answers the maths question
no_answer_message: "§cNo one answered the maths question, move on to the next maths question..."

# Delay when question is missed
maths_delay_solved: 5

# Rewards when players successfully answer maths questions
prize_min: 1000
prize_max: 10000

# Economy you are using (Must use LibPiggyEconomy)
Economy:
  type: "economyapi" # Change this to your specific economy provider if needed (bedrockeconomy/economyapi)